"use client";

import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// Translations
const translations = {
  en: {
    // Navbar
    nav: {
      dashboard: "Dashboard",
      strategies: "Strategies",
      backtest: "Backtest",
      connect: "Connect",
      pricing: "Pricing",
      signIn: "Sign in",
      getStarted: "Get started",
      myProfile: "My Profile",
      achievements: "Achievements",
      myStrategies: "My Strategies",
      connectExchange: "Connect Exchange",
      upgradePlan: "Upgrade Plan",
      settings: "Settings",
      logOut: "Log Out",
    },
    
    // Hero
    hero: {
      title: "Automate Your",
      titleHighlight: "Crypto Trading",
      subtitle: "Build, backtest, and deploy algorithmic trading strategies. No coding required.",
      cta: "Start Trading",
      ctaSecondary: "View Strategies",
      stats: {
        users: "Active Traders",
        strategies: "Strategies",
        volume: "Trading Volume",
      },
    },
    
    // Landing page
    landing: {
      sampleGrowth: "Sample Portfolio Growth",
      yearly: "yearly",
      starting: "Starting",
      final: "Final",
      maxDD: "Max DD",
      featuredStrategies: "Featured Strategies",
      viewAll: "View all →",
      live: "Live",
      yr: "/yr",
      loadingStrategies: "Loading strategies from real market data...",
      checkBackSoon: "Please check back soon.",
      metricsNote: "📊 All metrics are calculated from real historical market data and updated hourly.",
      
      // How it works
      howItWorks: "How It Works",
      howItWorksSubtitle: "Start automated trading in 3 simple steps. No coding required.",
      step1Title: "Choose a Strategy",
      step1Text: "Browse our curated strategies with real performance data, or build your own using our visual backtester.",
      step2Title: "Connect Exchange",
      step2Text: "Link your Binance, Bybit, or OKX account with API keys. We only need trading permissions, never withdrawals.",
      step3Title: "Start Trading",
      step3Text: "Activate your strategy and let it trade 24/7. Monitor performance in real-time from your dashboard.",
      getStartedFree: "Get Started Free →",
      
      // Why Algotcha
      whyAlgotcha: "Why Algotcha?",
      realData: "Real Data",
      realDataText: "5 years of minute-by-minute historical data. No fake backtests.",
      secure: "Secure",
      secureText: "Your API keys are encrypted. Trading only — never withdrawals.",
      fastExecution: "Fast Execution",
      fastExecutionText: "Dedicated trading server with static IP for reliable order execution.",
      transparent: "Transparent",
      transparentText: "See every trade with indicator proof. No black box algorithms.",
      
      // Testimonials
      testimonials: "What Our Users Say",
      testimonialsSubtitle: "Real reviews from traders who have automated their trading with Algotcha",
      ssl: "256-bit SSL",
      verifiedReviews: "Verified Reviews",
      ukrainianPlatform: "Ukrainian Platform",
      
      // CTA
      readyToAutomate: "Ready to automate your trading?",
      ctaSubtitle: "Join thousands of traders using algorithmic strategies to grow their portfolios.",
      createFreeAccount: "Create Free Account",
      viewStrategies: "View Strategies",
    },
    
    // Account page
    account: {
      overview: "Overview",
      achievements: "Achievements",
      settings: "Settings",
      backtestsRun: "Backtests Run",
      totalAnalyses: "Total analyses",
      activeStrategies: "Active Strategies",
      runningNow: "Running now",
      totalProfit: "Total Profit",
      allTime: "All time",
      winRate: "Win Rate",
      trades: "trades",
      recentAchievements: "Recent Achievements",
      viewAllAchievements: "View All",
      runBacktest: "Run Backtest",
      runBacktestText: "Test your strategy against historical data",
      browseStrategies: "Browse Strategies",
      browseStrategiesText: "Explore top-performing strategies",
      connectExchangeText: "Start live trading with your API",
      memberSince: "Member since",
      unlocked: "Unlocked",
      xpEarned: "XP earned",
      level: "Level",
      progress: "Progress",
      profileSettings: "Profile Settings",
      personalInfo: "Personal Information",
      fullName: "Full Name",
      email: "Email",
      country: "Country",
      phone: "Phone",
      socialLinks: "Social Links",
      saveChanges: "Save Changes",
      saving: "Saving...",
      subscription: "Subscription",
      freePlan: "Free Plan",
      freePlanText: "Basic features • 3 backtests/day",
      upgrade: "Upgrade",
    },
    
    // Achievements
    achievements: {
      firstSteps: "First Steps",
      firstStepsDesc: "Run your first backtest",
      strategyCreator: "Strategy Creator",
      strategyCreatorDesc: "Save your first strategy",
      liveTrader: "Live Trader",
      liveTraderDesc: "Start your first live strategy",
      profitMaker: "Profit Maker",
      profitMakerDesc: "Achieve your first profitable trade",
      backtesterPro: "Backtester Pro",
      backtesterProDesc: "Run 10 backtests",
      diversified: "Diversified",
      diversifiedDesc: "Trade 5 different pairs",
      consistent: "Consistent",
      consistentDesc: "Maintain a 60%+ win rate over 50 trades",
      whale: "Whale",
      whaleDesc: "Achieve $10,000+ in total profit",
    },
    
    // Footer
    footer: {
      description: "Automate your crypto trading with powerful algorithmic strategies. Built for traders, by traders.",
      product: "Product",
      company: "Company",
      legal: "Legal",
      about: "About Us",
      faq: "FAQ",
      support: "Support",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
      risk: "Risk Disclosure",
      allRightsReserved: "All rights reserved.",
    },
    
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      back: "Back",
      next: "Next",
      submit: "Submit",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      noResults: "No results found",
      tryAgain: "Try again",
    },
    
    // Testimonials content
    testimonialContent: {
      oleg: "Before this, trading honestly felt like throwing darts in the dark. Now I can really tell what looks good before I even risk a dollar.",
      nazar: "I'm sitting here wondering why I ever paid some guy to do what this thing does on its own for way less.",
      dmytro: "Using Algotcha feels like letting your smartest friend do the hard part while you just relax.",
      karina: "Feels like Wall Street on autopilot, but simple enough that even I can run it without overthinking.",
    },
    
    // Connect page
    connect: {
      title: "Connect Your Exchange",
      subtitle: "Connect your exchange account to start automated trading. We only need trading permissions — never withdrawal access.",
      securityFirst: "Security First",
      securityBullets: [
        "API keys are stored encrypted and never shared",
        "Create keys with trading only permissions (no withdrawals)",
        "Use testnet for testing before going live",
        "You can revoke access anytime from your exchange"
      ],
      ipWhitelisting: "IP Whitelisting (Recommended)",
      ipWhitelistingDesc: "For maximum security, whitelist our trading server IP on your exchange:",
      copy: "Copy",
      ipWhitelistingNote: "This ensures only our server can execute trades with your API keys.",
      apiKey: "API Key",
      apiSecret: "API Secret",
      passphrase: "Passphrase (optional)",
      passphraseNote: "Only required for OKX",
      useTestnet: "Use Testnet (recommended for testing)",
      connect: "Connect",
      reconnect: "Reconnect",
      connecting: "Connecting...",
      testBalance: "Test Balance",
      testing: "Testing...",
      howToCreate: "How to create API keys →",
      getTestnet: "Get testnet account →",
      connected: "Exchange Connected!",
      readyToTrade: "You're ready to start trading. Here's what you can do next:",
      createStrategy: "Create Strategy",
      goToDashboard: "Go to Dashboard",
      needHelp: "Need help?",
      checkFaq: "Check our FAQ",
      contactSupport: "contact support",
      loginRequired: "Login Required",
      loginToConnect: "You need to be logged in to connect your exchange account.",
      loginSignup: "Login / Sign Up",
      balanceSuccess: "Balance fetched successfully",
      noAssets: "No assets (balance is 0)",
      connectionFailed: "Connection failed",
      invalidCredentials: "Invalid API key or secret. Please check your credentials.",
      networkError: "Network error. Please check your connection and try again.",
      unsupportedExchange: "Unsupported exchange",
    },
    
    // Strategies page
    strategies: {
      title: "Trading Strategies",
      subtitle: "Real performance data updated every hour from historical backtests",
      createCustom: "+ Create Custom Strategy",
      searchPlaceholder: "Search strategies...",
      sortBy: "Sort by:",
      yearlyReturn: "Yearly Return",
      sharpeRatio: "Sharpe Ratio",
      winRate: "Win Rate",
      lowestDrawdown: "Lowest Drawdown",
      refresh: "Refresh",
      activeStrategies: "Active Strategies",
      bestYearly: "Best Yearly Return",
      bestSharpe: "Best Sharpe Ratio",
      avgWinRate: "Avg Win Rate",
      savedStrategies: "Your Saved Strategies",
      yourStrategy: "Your Strategy",
      profit: "Profit",
      maxDD: "Max DD",
      useStrategy: "Use Strategy",
      featured: "🌟 Featured Strategies",
      noStrategies: "No strategies available yet.",
      calculating: "Strategies are being calculated from real market data. Please check back soon.",
      daily: "Daily",
      weekly: "Weekly",
      monthly: "Monthly",
      updated: "Updated",
      viewDetails: "View Details",
      noMatch: "No strategies found matching your search.",
      dataNote: "📊 Real Performance Data: All metrics are calculated from actual historical price data from Binance and updated automatically every hour. Past performance does not guarantee future results.",
    },
    
    // Backtest page
    backtest: {
      title: "Strategy Backtest",
      subtitle: "Build, test, and optimize your trading strategies",
      strategySettings: "Strategy Settings",
      strategyName: "Strategy Name",
      maxActiveDeals: "Max Active Deals",
      initialBalance: "Initial Balance ($)",
      baseOrderSize: "Base Order Size ($)",
      startDate: "Start Date",
      endDate: "End Date",
      tradingPairs: "Trading Pairs",
      riskManagement: "Risk Management",
      takeProfit: "Take Profit (%)",
      takeProfitDesc: "Close position at this profit %",
      stopLoss: "Stop Loss (%)",
      stopLossDesc: "Close position at this loss %",
      enableTrailingStop: "Enable Trailing Stop",
      safetyOrders: "Safety Orders (DCA)",
      numSafetyOrders: "Number of Safety Orders",
      priceDeviation: "Price Deviation (%)",
      priceDeviationDesc: "Drop % to trigger each SO",
      volumeScale: "Volume Scale",
      volumeScaleDesc: "Multiply each SO size",
      dcaStrategy: "DCA Strategy:",
      dcaStrategyDesc: "If price drops {deviation}%, place safety order at {scale}x base size. Max {count} safety orders.",
      marketStateConditions: "Use Market State Conditions",
      marketStateDesc: "Enable separate bullish/bearish conditions based on BTC market state",
      entryConditions: "Entry Conditions",
      exitConditions: "Exit Conditions",
      addCondition: "+ Add Condition",
      noEntryConditions: "No entry conditions. Add one to start.",
      noExitConditions: "No exit conditions. Add one to complete your strategy.",
      bullishEntry: "🐂 Bullish Entry",
      bullishExit: "🐂 Bullish Exit",
      bearishEntry: "🐻 Bearish Entry",
      bearishExit: "🐻 Bearish Exit",
      add: "+ Add",
      runBacktest: "🚀 Run Backtest",
      runningBacktest: "Running Backtest...",
      likeResults: "Like these results?",
      saveToRunLive: "Save this strategy to run it live",
      saveStrategy: "💾 Save Strategy",
      saving: "Saving...",
      saved: "✓ Saved!",
      savedNote: "Strategy saved! Go to Strategies to view or Dashboard to start trading.",
      exportReport: "Export Trade Report",
      downloadCSV: "📥 Download CSV",
      printPDF: "📄 Print PDF Report",
      exportTrades: "Export {count} trades for your records",
      performanceMetrics: "Performance Metrics",
      netProfit: "Net Profit",
      maxDrawdown: "Max Drawdown",
      totalTrades: "Total Trades",
      profitFactor: "Profit Factor",
      sortinoRatio: "Sortino Ratio",
      yearlyReturn: "Yearly Return",
      equityCurve: "Equity Curve",
      drawdown: "Drawdown",
      tradeHistory: "Trade History",
      tradesCount: "{count} trades",
      transparency: "Full transparency with indicator proof",
      dateTime: "Date & Time",
      pair: "Pair",
      action: "Action",
      price: "Price",
      pnl: "P&L",
      equity: "Equity",
      dd: "DD",
      reason: "Reason",
      indicatorProof: "Indicator Proof",
      showingFirst: "Showing first 50 of {total} trades. Download full report for all trades.",
      noResultsYet: "No Results Yet",
      configureToSee: "Configure your strategy and run a backtest to see results here.",
      // Condition builder
      remove: "Remove",
      timeframe: "Timeframe",
      rsiLength: "RSI Length",
      condition: "Condition",
      signalValue: "Signal Value",
      maPeriod: "MA Period",
      maType: "MA Type",
      fastPeriod: "Fast Period",
      slowPeriod: "Slow Period",
      signalPeriod: "Signal Period",
      macdLine: "MACD Line",
      bbPeriod: "BB Period",
      bbStdDev: "BB Std Dev",
      lessThan: "Less Than",
      greaterThan: "Greater Than",
      crossingUp: "Crossing Up",
      crossingDown: "Crossing Down",
    },
    
    // Dashboard
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome back!",
      portfolioValue: "Portfolio Value",
      todayPnL: "Today's P&L",
      activeStrategies: "Active Strategies",
      totalTrades: "Total Trades",
      recentTrades: "Recent Trades",
      noTrades: "No trades yet. Activate a strategy to start trading.",
      yourStrategies: "Your Strategies",
      noStrategies: "No active strategies. Go to Strategies to activate one.",
      goToStrategies: "Go to Strategies",
      performance: "Performance",
      daily: "Daily",
      weekly: "Weekly",
      monthly: "Monthly",
      allTime: "All Time",
    },
    
    // Pricing
    pricing: {
      title: "Pricing Plans",
      subtitle: "Choose the plan that's right for you",
      monthly: "Monthly",
      yearly: "Yearly",
      savePercent: "Save 20%",
      free: "Free",
      freePrice: "$0",
      freeDesc: "Get started with basic features",
      freeFeatures: [
        "3 backtests per day",
        "1 active strategy",
        "Basic indicators",
        "Community support"
      ],
      pro: "Pro",
      proPrice: "$29/mo",
      proDesc: "For serious traders",
      proFeatures: [
        "Unlimited backtests",
        "5 active strategies",
        "All indicators",
        "Priority support",
        "Advanced risk management"
      ],
      enterprise: "Enterprise",
      enterprisePrice: "Custom",
      enterpriseDesc: "For trading firms",
      enterpriseFeatures: [
        "Everything in Pro",
        "Unlimited strategies",
        "Dedicated server",
        "Custom indicators",
        "Personal account manager"
      ],
      currentPlan: "Current Plan",
      upgrade: "Upgrade",
      contactUs: "Contact Us",
      popular: "Popular",
    },
    
    // Partners
    partners: {
      title: "Our Partners & Integrations",
      exchanges: "Exchanges",
      dataProviders: "Data Providers",
      techPartners: "Tech Partners",
    },
  },
  
  uk: {
    // Navbar
    nav: {
      dashboard: "Панель",
      strategies: "Стратегії",
      backtest: "Бектест",
      connect: "Підключення",
      pricing: "Тарифи",
      signIn: "Увійти",
      getStarted: "Почати",
      myProfile: "Мій профіль",
      achievements: "Досягнення",
      myStrategies: "Мої стратегії",
      connectExchange: "Підключити біржу",
      upgradePlan: "Покращити план",
      settings: "Налаштування",
      logOut: "Вийти",
    },
    
    // Hero
    hero: {
      title: "Автоматизуй свою",
      titleHighlight: "Крипто-торгівлю",
      subtitle: "Створюй, тестуй та запускай алгоритмічні торгові стратегії. Без програмування.",
      cta: "Почати торгувати",
      ctaSecondary: "Переглянути стратегії",
      stats: {
        users: "Активних трейдерів",
        strategies: "Стратегій",
        volume: "Обсяг торгів",
      },
    },
    
    // Landing page
    landing: {
      sampleGrowth: "Приклад зростання портфеля",
      yearly: "на рік",
      starting: "Початок",
      final: "Кінець",
      maxDD: "Макс. просадка",
      featuredStrategies: "Популярні стратегії",
      viewAll: "Всі →",
      live: "Активна",
      yr: "/рік",
      loadingStrategies: "Завантаження стратегій з реальних ринкових даних...",
      checkBackSoon: "Будь ласка, перевірте пізніше.",
      metricsNote: "📊 Всі метрики розраховані на основі реальних історичних даних ринку та оновлюються щогодини.",
      
      // How it works
      howItWorks: "Як це працює",
      howItWorksSubtitle: "Почни автоматичну торгівлю за 3 простих кроки. Без програмування.",
      step1Title: "Обери стратегію",
      step1Text: "Переглянь готові стратегії з реальними показниками, або створи власну за допомогою візуального бектестера.",
      step2Title: "Підключи біржу",
      step2Text: "Зв'яжи свій Binance, Bybit або OKX акаунт через API. Нам потрібні лише права на торгівлю, ніколи на виведення.",
      step3Title: "Почни торгувати",
      step3Text: "Активуй стратегію і дозволь їй торгувати 24/7. Слідкуй за результатами в реальному часі з панелі управління.",
      getStartedFree: "Почати безкоштовно →",
      
      // Why Algotcha
      whyAlgotcha: "Чому Algotcha?",
      realData: "Реальні дані",
      realDataText: "5 років хвилинних історичних даних. Жодних фейкових бектестів.",
      secure: "Безпечно",
      secureText: "Ваші API ключі зашифровані. Тільки торгівля — ніколи виведення.",
      fastExecution: "Швидке виконання",
      fastExecutionText: "Виділений торговий сервер зі статичним IP для надійного виконання ордерів.",
      transparent: "Прозоро",
      transparentText: "Бачте кожну угоду з доказами по індикаторах. Жодних чорних ящиків.",
      
      // Testimonials
      testimonials: "Що кажуть наші користувачі",
      testimonialsSubtitle: "Реальні відгуки від трейдерів, які вже автоматизували свою торгівлю з Algotcha",
      ssl: "256-bit SSL",
      verifiedReviews: "Верифіковані відгуки",
      ukrainianPlatform: "Українська платформа",
      
      // CTA
      readyToAutomate: "Готові автоматизувати торгівлю?",
      ctaSubtitle: "Приєднуйтесь до тисяч трейдерів, які використовують алгоритмічні стратегії для зростання своїх портфелів.",
      createFreeAccount: "Створити безкоштовний акаунт",
      viewStrategies: "Переглянути стратегії",
    },
    
    // Account page
    account: {
      overview: "Огляд",
      achievements: "Досягнення",
      settings: "Налаштування",
      backtestsRun: "Бектестів запущено",
      totalAnalyses: "Всього аналізів",
      activeStrategies: "Активних стратегій",
      runningNow: "Зараз працюють",
      totalProfit: "Загальний прибуток",
      allTime: "За весь час",
      winRate: "Відсоток виграшу",
      trades: "угод",
      recentAchievements: "Останні досягнення",
      viewAllAchievements: "Переглянути всі",
      runBacktest: "Запустити бектест",
      runBacktestText: "Протестуй стратегію на історичних даних",
      browseStrategies: "Переглянути стратегії",
      browseStrategiesText: "Досліджуй найкращі стратегії",
      connectExchangeText: "Почни живу торгівлю зі своїм API",
      memberSince: "Учасник з",
      unlocked: "Відкрито",
      xpEarned: "Зароблено XP",
      level: "Рівень",
      progress: "Прогрес",
      profileSettings: "Налаштування профілю",
      personalInfo: "Особиста інформація",
      fullName: "Повне ім'я",
      email: "Електронна пошта",
      country: "Країна",
      phone: "Телефон",
      socialLinks: "Соціальні мережі",
      saveChanges: "Зберегти зміни",
      saving: "Збереження...",
      subscription: "Підписка",
      freePlan: "Безкоштовний план",
      freePlanText: "Базові функції • 3 бектести/день",
      upgrade: "Покращити",
    },
    
    // Achievements
    achievements: {
      firstSteps: "Перші кроки",
      firstStepsDesc: "Запусти свій перший бектест",
      strategyCreator: "Творець стратегій",
      strategyCreatorDesc: "Збережи свою першу стратегію",
      liveTrader: "Живий трейдер",
      liveTraderDesc: "Запусти свою першу живу стратегію",
      profitMaker: "Прибуткотворець",
      profitMakerDesc: "Здійсни свою першу прибуткову угоду",
      backtesterPro: "Бектестер Про",
      backtesterProDesc: "Запусти 10 бектестів",
      diversified: "Диверсифікований",
      diversifiedDesc: "Торгуй 5 різними парами",
      consistent: "Послідовний",
      consistentDesc: "Підтримуй 60%+ відсоток виграшу на 50 угодах",
      whale: "Кит",
      whaleDesc: "Досягни $10,000+ загального прибутку",
    },
    
    // Footer
    footer: {
      description: "Автоматизуй свою крипто-торгівлю за допомогою потужних алгоритмічних стратегій. Створено трейдерами для трейдерів.",
      product: "Продукт",
      company: "Компанія",
      legal: "Правова інформація",
      about: "Про нас",
      faq: "Питання та відповіді",
      support: "Підтримка",
      terms: "Умови використання",
      privacy: "Політика конфіденційності",
      risk: "Розкриття ризиків",
      allRightsReserved: "Всі права захищені.",
    },
    
    // Common
    common: {
      loading: "Завантаження...",
      error: "Помилка",
      success: "Успішно",
      cancel: "Скасувати",
      save: "Зберегти",
      delete: "Видалити",
      edit: "Редагувати",
      close: "Закрити",
      back: "Назад",
      next: "Далі",
      submit: "Надіслати",
      search: "Пошук",
      filter: "Фільтр",
      sort: "Сортувати",
      noResults: "Результатів не знайдено",
      tryAgain: "Спробуй ще раз",
    },
    
    // Testimonials content
    testimonialContent: {
      oleg: "Раніше торгівля чесно відчувалась як кидання дротиків наосліп. Тепер я можу реально бачити, що виглядає перспективно, ще до того, як ризикую хоч долар.",
      nazar: "Сиджу і думаю, навіщо я раніше платив комусь за те, що ця штука робить сама і набагато дешевше.",
      dmytro: "Користуватись Algotcha — це як дати своєму найрозумнішому другу зробити всю важку роботу, поки ти просто відпочиваєш.",
      karina: "Відчуття, ніби Волл-стріт на автопілоті, але настільки просто, що навіть я можу керувати цим без зайвих роздумів.",
    },
    
    // Connect page
    connect: {
      title: "Підключення біржі",
      subtitle: "Підключіть свій акаунт біржі для початку автоматичної торгівлі. Нам потрібні лише права на торгівлю — ніколи на виведення.",
      securityFirst: "Безпека перш за все",
      securityBullets: [
        "API ключі зберігаються зашифрованими та ніколи не передаються",
        "Створюйте ключі лише з правами на торгівлю (без виведення)",
        "Використовуйте тестнет для тестування перед запуском",
        "Ви можете відкликати доступ будь-коли з біржі"
      ],
      ipWhitelisting: "Білий список IP (Рекомендовано)",
      ipWhitelistingDesc: "Для максимальної безпеки додайте IP нашого торгового сервера в білий список на біржі:",
      copy: "Копіювати",
      ipWhitelistingNote: "Це гарантує, що тільки наш сервер зможе виконувати угоди з вашими API ключами.",
      apiKey: "API Ключ",
      apiSecret: "API Секрет",
      passphrase: "Парольна фраза (опціонально)",
      passphraseNote: "Потрібна лише для OKX",
      useTestnet: "Використовувати Testnet (рекомендовано для тестування)",
      connect: "Підключити",
      reconnect: "Перепідключити",
      connecting: "Підключення...",
      testBalance: "Перевірити баланс",
      testing: "Тестування...",
      howToCreate: "Як створити API ключі →",
      getTestnet: "Отримати testnet акаунт →",
      connected: "Біржа підключена!",
      readyToTrade: "Ви готові до торгівлі. Ось що можна зробити далі:",
      createStrategy: "Створити стратегію",
      goToDashboard: "Перейти до панелі",
      needHelp: "Потрібна допомога?",
      checkFaq: "Перегляньте наші FAQ",
      contactSupport: "зв'яжіться з підтримкою",
      loginRequired: "Потрібна авторизація",
      loginToConnect: "Увійдіть, щоб підключити акаунт біржі.",
      loginSignup: "Увійти / Зареєструватися",
      balanceSuccess: "Баланс успішно отримано",
      noAssets: "Немає активів (баланс 0)",
      connectionFailed: "Помилка підключення",
      invalidCredentials: "Недійсний API ключ або секрет. Перевірте свої дані.",
      networkError: "Помилка мережі. Перевірте підключення та спробуйте ще раз.",
      unsupportedExchange: "Біржа не підтримується",
    },
    
    // Strategies page
    strategies: {
      title: "Торгові стратегії",
      subtitle: "Реальні показники ефективності оновлюються щогодини на основі історичних бектестів",
      createCustom: "+ Створити свою стратегію",
      searchPlaceholder: "Пошук стратегій...",
      sortBy: "Сортувати за:",
      yearlyReturn: "Річною дохідністю",
      sharpeRatio: "Коефіцієнтом Шарпа",
      winRate: "Відсотком виграшу",
      lowestDrawdown: "Найменшою просадкою",
      refresh: "Оновити",
      activeStrategies: "Активних стратегій",
      bestYearly: "Найкраща річна дохідність",
      bestSharpe: "Найкращий коефіцієнт Шарпа",
      avgWinRate: "Середній відсоток виграшу",
      savedStrategies: "Ваші збережені стратегії",
      yourStrategy: "Ваша стратегія",
      profit: "Прибуток",
      maxDD: "Макс. просадка",
      useStrategy: "Використати",
      featured: "🌟 Популярні стратегії",
      noStrategies: "Стратегій поки немає.",
      calculating: "Стратегії розраховуються на основі реальних ринкових даних. Перевірте пізніше.",
      daily: "Денна",
      weekly: "Тижнева",
      monthly: "Місячна",
      updated: "Оновлено",
      viewDetails: "Детальніше",
      noMatch: "Стратегій за вашим запитом не знайдено.",
      dataNote: "📊 Реальні дані: Всі метрики розраховані на основі фактичних історичних цін з Binance та оновлюються автоматично щогодини. Минулі результати не гарантують майбутніх.",
    },
    
    // Backtest page
    backtest: {
      title: "Бектест стратегії",
      subtitle: "Створюй, тестуй та оптимізуй свої торгові стратегії",
      strategySettings: "Налаштування стратегії",
      strategyName: "Назва стратегії",
      maxActiveDeals: "Макс. активних угод",
      initialBalance: "Початковий баланс ($)",
      baseOrderSize: "Розмір базового ордеру ($)",
      startDate: "Дата початку",
      endDate: "Дата кінця",
      tradingPairs: "Торгові пари",
      riskManagement: "Управління ризиками",
      takeProfit: "Take Profit (%)",
      takeProfitDesc: "Закрити позицію при цьому % прибутку",
      stopLoss: "Stop Loss (%)",
      stopLossDesc: "Закрити позицію при цьому % збитку",
      enableTrailingStop: "Увімкнути Trailing Stop",
      safetyOrders: "Safety Orders (DCA)",
      numSafetyOrders: "Кількість Safety Orders",
      priceDeviation: "Відхилення ціни (%)",
      priceDeviationDesc: "% падіння для спрацювання SO",
      volumeScale: "Масштаб обсягу",
      volumeScaleDesc: "Помножити кожен SO на",
      dcaStrategy: "DCA Стратегія:",
      dcaStrategyDesc: "При падінні на {deviation}%, розмістити safety order у {scale}x від базового. Макс. {count} safety orders.",
      marketStateConditions: "Використовувати умови стану ринку",
      marketStateDesc: "Увімкнути окремі умови для бичачого/ведмежого ринку на основі BTC",
      entryConditions: "Умови входу",
      exitConditions: "Умови виходу",
      addCondition: "+ Додати умову",
      noEntryConditions: "Немає умов входу. Додайте одну для початку.",
      noExitConditions: "Немає умов виходу. Додайте одну для завершення стратегії.",
      bullishEntry: "🐂 Бичачий вхід",
      bullishExit: "🐂 Бичачий вихід",
      bearishEntry: "🐻 Ведмежий вхід",
      bearishExit: "🐻 Ведмежий вихід",
      add: "+ Додати",
      runBacktest: "🚀 Запустити бектест",
      runningBacktest: "Виконання бектесту...",
      likeResults: "Подобаються результати?",
      saveToRunLive: "Збережіть стратегію для запуску наживо",
      saveStrategy: "💾 Зберегти стратегію",
      saving: "Збереження...",
      saved: "✓ Збережено!",
      savedNote: "Стратегія збережена! Перейдіть до Стратегій для перегляду або Панелі для початку торгівлі.",
      exportReport: "Експорт звіту по угодах",
      downloadCSV: "📥 Завантажити CSV",
      printPDF: "📄 Друк PDF звіту",
      exportTrades: "Експорт {count} угод для ваших записів",
      performanceMetrics: "Показники ефективності",
      netProfit: "Чистий прибуток",
      maxDrawdown: "Макс. просадка",
      totalTrades: "Всього угод",
      profitFactor: "Profit Factor",
      sortinoRatio: "Sortino Ratio",
      yearlyReturn: "Річна дохідність",
      equityCurve: "Крива капіталу",
      drawdown: "Просадка",
      tradeHistory: "Історія угод",
      tradesCount: "{count} угод",
      transparency: "Повна прозорість з доказами по індикаторах",
      dateTime: "Дата і час",
      pair: "Пара",
      action: "Дія",
      price: "Ціна",
      pnl: "P&L",
      equity: "Капітал",
      dd: "DD",
      reason: "Причина",
      indicatorProof: "Докази індикаторів",
      showingFirst: "Показано перші 50 з {total} угод. Завантажте повний звіт для всіх угод.",
      noResultsYet: "Ще немає результатів",
      configureToSee: "Налаштуйте стратегію та запустіть бектест, щоб побачити результати тут.",
      // Condition builder
      remove: "Видалити",
      timeframe: "Таймфрейм",
      rsiLength: "Період RSI",
      condition: "Умова",
      signalValue: "Сигнальне значення",
      maPeriod: "Період MA",
      maType: "Тип MA",
      fastPeriod: "Швидкий період",
      slowPeriod: "Повільний період",
      signalPeriod: "Сигнальний період",
      macdLine: "Лінія MACD",
      bbPeriod: "Період BB",
      bbStdDev: "Ст. відхилення BB",
      lessThan: "Менше ніж",
      greaterThan: "Більше ніж",
      crossingUp: "Перетин вгору",
      crossingDown: "Перетин вниз",
    },
    
    // Dashboard
    dashboard: {
      title: "Панель управління",
      welcome: "З поверненням!",
      portfolioValue: "Вартість портфеля",
      todayPnL: "Сьогоднішній P&L",
      activeStrategies: "Активних стратегій",
      totalTrades: "Всього угод",
      recentTrades: "Останні угоди",
      noTrades: "Угод ще немає. Активуйте стратегію для початку торгівлі.",
      yourStrategies: "Ваші стратегії",
      noStrategies: "Немає активних стратегій. Перейдіть до Стратегій для активації.",
      goToStrategies: "Перейти до стратегій",
      performance: "Показники",
      daily: "День",
      weekly: "Тиждень",
      monthly: "Місяць",
      allTime: "Весь час",
    },
    
    // Pricing
    pricing: {
      title: "Тарифні плани",
      subtitle: "Оберіть план, який вам підходить",
      monthly: "Щомісячно",
      yearly: "Щорічно",
      savePercent: "Економія 20%",
      free: "Безкоштовний",
      freePrice: "$0",
      freeDesc: "Почніть з базових функцій",
      freeFeatures: [
        "3 бектести на день",
        "1 активна стратегія",
        "Базові індикатори",
        "Підтримка спільноти"
      ],
      pro: "Pro",
      proPrice: "$29/міс",
      proDesc: "Для серйозних трейдерів",
      proFeatures: [
        "Необмежені бектести",
        "5 активних стратегій",
        "Всі індикатори",
        "Пріоритетна підтримка",
        "Розширене управління ризиками"
      ],
      enterprise: "Enterprise",
      enterprisePrice: "Індивідуально",
      enterpriseDesc: "Для торгових компаній",
      enterpriseFeatures: [
        "Все з Pro",
        "Необмежені стратегії",
        "Виділений сервер",
        "Кастомні індикатори",
        "Персональний менеджер"
      ],
      currentPlan: "Поточний план",
      upgrade: "Покращити",
      contactUs: "Зв'язатися",
      popular: "Популярний",
    },
    
    // Partners
    partners: {
      title: "Наші партнери та інтеграції",
      exchanges: "Біржі",
      dataProviders: "Постачальники даних",
      techPartners: "Технологічні партнери",
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("uk"); // Default to Ukrainian

  useEffect(() => {
    // Load saved language preference
    const saved = localStorage.getItem("algotcha-language");
    if (saved && (saved === "en" || saved === "uk")) {
      setLanguage(saved);
    }
  }, []);

  const toggleLanguage = () => {
    const newLang = language === "en" ? "uk" : "en";
    setLanguage(newLang);
    localStorage.setItem("algotcha-language", newLang);
  };

  const setLang = (lang) => {
    if (lang === "en" || lang === "uk") {
      setLanguage(lang);
      localStorage.setItem("algotcha-language", lang);
    }
  };

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

